### ISSUE TITLE
Sample chefregistrationetc.txt

### ISSUE THREAD

**Issue by saiaman** [atrull/cassandra_priam_cookbook#3]
Hello do you have any sample file for chefregistrationetc.txt ?

Thanks for help

**Comment by atrull** [comment]
Chef registration is a shell script to install chef, and register the node with the chef server/start chef-client.

You need to provide your own validation key to do it (this is needed to register the node) and also, optionally, the shared databag secret key.

If you still need help with this, please let me know.
